[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "GRC"
version = ""
authors = []
description = "GNU Radio Companion"
readme = "README.md"
requires-python = ""
classifiers = []

[project.urls]
